name = "mulyono"
main = "_worker.js"
compatibility_date = "2026-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "f7b6ec53-9f5c-4205-a5db-dd25f008c567"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
