name = "mulyono"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "95.164.4.252"
UUID = "f7b6ec53-9f5c-4205-a5db-dd25f008c567"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
